from enum import Enum


class TimeScale(str, Enum):
    """Enumeration of the allowed time scales in the IVOA vocabulary."""

    GPS = "GPS"
    """Global Positioning System time"""
    TAI = "TAI"
    """International Atomic Time"""
    TCB = "TCB"
    """Barycentric Coordinate Time"""
    TCG = "TCG"
    """Geocentric Coordinate Time"""
    TDB = "TDB"
    """Barycentric Dynamical Time"""
    TT = "TT"
    """Terrestrial Time"""
    UT = "UT"
    """Earth Rotation Time"""
    UTC = "UTC"
    """Coordinated Universal Time"""
    UNKNOWN = "UNKNOWN"
    """Unknown or unavailable time scale"""

class ReferenceFrame(str, Enum):
    """Enumeration of the allowed reference frames in the IVOA vocabulary."""

    AZ_EL = "AZ-EL"
    """Azimuth-Elevation"""
    BODY = "BODY"
    """Body Coordinates"""
    ECLIPTIC = "ECLIPTIC"
    """Ecliptic Coordinates"""
    EQUATORIAL = "EQUATORIAL"
    """Equatorial Coordinates"""
    FK4 = "FK4"
    """Fourth Fundamental Catalog"""
    FK5 = "FK5"
    """Fifth Fundamental Catalog"""
    GALACTIC = "GALACTIC"
    """Galactic Coordinates"""
    GALACTIC_I = "GALACTIC_I"
    """Old Galactic Coordinates"""
    GENERIC_GALACTIC = "GENERIC_GALACTIC"
    """Umbrella term for Galactic coordinate systems"""
    ICRS = "ICRS"
    """International Celestial Reference System"""
    SUPER_GALACTIC = "SUPER_GALACTIC"
    """Super Galactic Coordinates"""
    UNKNOWN = "UNKNOWN"
    """Unknown or unavailable reference frame"""
    BARYCENTRIC = "BARYCENTRIC"
    """Barycentric Reference Frame"""

class ReferencePosition(str, Enum):
    """Enumeration of the allowed reference positions in the IVOA vocabulary."""

    BARY = "BARY"
    """Barycenter of the Solar System"""
    EMBARY = "EBARY"
    """Earth-Moon Barycenter"""
    GEO = "GEO"
    """Center of the Earth"""
    HELIO = "HELIO"
    """Center of the Sun"""
    TOPO = "TOPO"
    """Location of the observer"""
    UNKNOWN = "UNKNOWN"
    """Unknown or unavailable reference position"""