"""IVOA VOResource-v1.1.xsd pydantic-xml models"""

from vo_models.voresource.models import (
    AccessURL,
    Capability,
    Contact,
    Content,
    Creator,
    Curation,
    Date,
    Interface,
    MirrorURL,
    Organisation,
    Relationship,
    Resource,
    ResourceName,
    Rights,
    SecurityMethod,
    Service,
    Source,
    Validation,
    WebBrowser,
    WebService,
)
from vo_models.voresource.types import (
    AuthorityID,
    IdentifierURI,
    ResourceKey,
    UTCDateTime,
    UTCTimestamp,
    ValidationLevel,
)

__all__ = [
    "AccessURL",
    "AuthorityID",
    "Capability",
    "Contact",
    "Content",
    "Creator",
    "Curation",
    "Date",
    "IdentifierURI",
    "Interface",
    "MirrorURL",
    "Organisation",
    "Relationship",
    "Resource",
    "ResourceKey",
    "ResourceName",
    "Rights",
    "SecurityMethod",
    "Service",
    "Source",
    "UTCDateTime",
    "UTCTimestamp",
    "Validation",
    "ValidationLevel",
    "WebBrowser",
    "WebService",
]
